# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ks < Formula
  desc "Keystone 开放生态平台开发者工具链"
  homepage "https://github.com/wuhanyuhan/ks-devkit"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wuhanyuhan/ks-devkit/releases/download/v0.5.3/ks_0.5.3_darwin_amd64.tar.gz"
      sha256 "5ba97ff80b18eef68e58bfa2b21abd02071d15603e20019dfdce550ae4960487"

      define_method(:install) do
        bin.install "ks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wuhanyuhan/ks-devkit/releases/download/v0.5.3/ks_0.5.3_darwin_arm64.tar.gz"
      sha256 "f2e9a2239743663ce5af47a722811c218cee89d4648ae48b2867cba7d9d1770f"

      define_method(:install) do
        bin.install "ks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wuhanyuhan/ks-devkit/releases/download/v0.5.3/ks_0.5.3_linux_amd64.tar.gz"
      sha256 "075c885f5b7ee4f49fe830704dbbfc09f2814fedb3f3a0d776e8dc54fa129396"
      define_method(:install) do
        bin.install "ks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wuhanyuhan/ks-devkit/releases/download/v0.5.3/ks_0.5.3_linux_arm64.tar.gz"
      sha256 "c09db8e908e26eea05055fb8a388b8f88085f61b9f16f7dceb39f44a1ec2a429"
      define_method(:install) do
        bin.install "ks"
      end
    end
  end

  test do
    system "#{bin}/ks", "--version"
  end
end
