# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ks < Formula
  desc "Keystone 开放生态平台开发者工具链"
  homepage "https://github.com/wuhanyuhan/ks-devkit"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wuhanyuhan/ks-devkit/releases/download/v0.6.1/ks_0.6.1_darwin_amd64.tar.gz"
      sha256 "e0333c233d175c947ee2698f4964a3a8a559dec71050e7dc469cd73568b72c87"

      define_method(:install) do
        bin.install "ks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wuhanyuhan/ks-devkit/releases/download/v0.6.1/ks_0.6.1_darwin_arm64.tar.gz"
      sha256 "83ec7bf1bdcd7a1b88affa3e496b7e7df9ecf13c93b9a6535abfc908bdff7b3d"

      define_method(:install) do
        bin.install "ks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wuhanyuhan/ks-devkit/releases/download/v0.6.1/ks_0.6.1_linux_amd64.tar.gz"
      sha256 "d17f0b3138c3ef4a2071b0e2e55aedafd1122410f0b21b93b3f957ebdc4ca7db"
      define_method(:install) do
        bin.install "ks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wuhanyuhan/ks-devkit/releases/download/v0.6.1/ks_0.6.1_linux_arm64.tar.gz"
      sha256 "e91c50108cf7cda0262ef4840b6bcc4c32e0bf684a7bf4966391385d6d549344"
      define_method(:install) do
        bin.install "ks"
      end
    end
  end

  test do
    system "#{bin}/ks", "--version"
  end
end
